### PR TITLE
Upgrade to Purescript 0.11

### PR DESCRIPTION
**Pull request by berdario**
This should work once https://github.com/rgrempel/purescript-int-53/pull/10 is merged
(I tested it with `bower link` in the meanwhile)

### CODE REVIEW

**Comment by jacobstanley** [comment]
Happy to merge this when purescript-int is updated

**Comment by berdario** [comment]
purescript-int has been updated, tests now pass :)

**Comment by jacobstanley** [comment]
💯 thanks for pushing things through on `purescript-int-53`

**Comment by jacobstanley** [comment]
Released as `v2.0.0`

**Pull request merged**
