### PR TITLE
dependency updates

### PR DESCRIPTION
**Pull request by matthewleon**
A simple bower install was causing dependency conflicts. Furthermore, the dependency tree would cause a number of conflicts with any recently created/updated purescript project.

### CODE REVIEW

**Comment by matthewleon** [comment]
This is, naturally, failing the build on PSC 0.9.3. Is maintaining backward compatibility to that version essential to this project?

**Comment by jacobstanley** [comment]
I'm just trying to figure out what to do here, we are still using 0.9.3 at work so ideally we could stay compatible but I'm not sure that is possible. It's a shame semver doesn't really allow for this scenario.

**Comment by matthewleon** [comment]
Also not sure it's possible, as I suspect the latest versions of the core libraries use features that are not supported in 0.9.3.

One solution might be to fork this into two repos: one (potentially private) for Ambiata and one, maintaining compatibility with the latest PureScript, for the public. Not sure how you/Ambiata would feel about supporting the public repo.

**Comment by jacobstanley** [comment]
I think I'm probably just going to go with these updates, and if necessary we can create a private fork, I don't imagine it will be too long before we're off 0.9.3

**Comment by matthewleon** [comment]
Any plans for moving ahead with this?

**Comment by jacobstanley** [comment]
Merged and rebased this in #18

**Pull request closed without merging**
